[package]
name = "conrod_test"
version = "0.1.0"
authors = ["Aaron Miller <aaron.miller04@gmail.com>"]

[dependencies]
conrod = "*"
piston_window = "*"
pistoncore-window = "*"
gfx = { version = "0.12.0", optional = true }
